### ISSUE TITLE
Contact the maintainers of storybook

### ISSUE THREAD

**Issue by ndelangen** [Personare/react-storybook-decorator-github-corner#1]
Hey! awesome decorator, Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by caueops** [comment]
@ndelangen Thank you very much for the feedback!

Ok, I'm going to slack channel 💃

**Comment by caueops** [comment]
@ndelangen This link doesn't work :/ 

What is the new link of channel?

**Comment by ndelangen** [comment]
Whoops. old link!

Here's the new one:
[self-invite to storybook slack](https://now-examples-slackin-nqnzoygycp.now.sh/)

**Comment by caueops** [comment]
@ndelangen Thank you <3
